version: "3"
services:
  # ----------------------------------------
  # PORTAINER
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:9000:9000'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './portainer:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/localtime:/etc/localtime:ro'
    command: -H unix:///var/run/docker.sock


  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}sonarr:/config
      - ${GMEDIA_TV}
      - ${DOWNLOAD}
    ports:
      - 8989:8989

  radarr:
    image: ghcr.io/linuxserver/radarr:nightly
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}radarr:/config
      - ${GMEDIA_MOVIE}
      - ${DOWNLOAD}
    ports:
      - 7878:7878

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}sabnzdb:/config
      - ${DOWNLOAD}
    ports:
      - 8080:8080

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - USER={TRANSUSER}
      - PASS={TRANSPASS}
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=france,sweden,austria,italy,belgium
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - LOCAL_NETWORK=192.168.0.0/16
    volumes:
      - ${APPDATA}transmission:/config
      - ${DOWNLOAD}
      - ${WATCH}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp


  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}ombi:/config
    ports:
      - 3579:3579

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${USVC}
      - PGID=${GSVC}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    volumes:
      - ${APPDATA}jackett:/config
    ports:
      - 9117:9117

  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}tautulli:/config
    ports:
      - 8181:8181

  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    restart: unless-stopped
    network_mode: host
    ports:
      # Port listing from Plex website as of 2019-08-18.
      # https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
      # Disabled 1900 and 5353 as of 2019-08-18.
      # Was running into some sort of conflict when trying to map them with bridge mode.
      # Something else on the NAS is using those ports -- home assistant perhaps?
      # The ports are for Plex services I don't necessarily need, so they are disabled for now.
      # - "1900:1900/udp" # (for access to the Plex DLNA Server)
      # - "5353:5353/udp" # (for older Bonjour/Avahi network discovery)

      - "32400:32400" # (for access to the Plex Media Server) [required]
      - "3005:3005" # (for controlling Plex Home Theater via Plex Companion)
      - "8324:8324" # (for controlling Plex for Roku via Plex Companion)
      - "32410:32410/udp" # (for current GDM network discovery)
      - "32412:32412/udp" # (for current GDM network discovery)
      - "32413:32413/udp" # (for current GDM network discovery)
      - "32414:32414/udp" # (for current GDM network discovery)
      - "32469:32469" # (for access to the Plex DLNA Server)

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${APPDATA}plex:/config
      - ${GMEDIA}


  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
